name: Trigger Lambda

on:
  pull_request:
    types:
      - merged

jobs:
  trigger_lambda:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
      FUNCTION_NAME: ${{ secrets.FUNCTION_NAME }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Run Lambda
        run: |
          aws lambda invoke --function-name ${{ env.FUNCTION_NAME }} --payload '{"key":"value"}' response.json
          cat response.json  # Print the Lambda response to the workflow log
